version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
  web_prod:
    build:
      context: .
    image: phoenix-prod
    depends_on:
      - db
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/myapp_prod
      - SECRET_KEY_BASE=xkjshdbajshdbjbdcfyvghjbasjdhbasjhdbkajshbdjsbdjlabsasdhabdhasdjhabksjdhba
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: mix phx.server
  web:
    build:
      context: .
    image: phoenix-base
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=db
    ports:
      - "4000:4000"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - .:/app
    command: mix phx.server
  test:
    build:
      context: .
    image: phoenix-base-test
    depends_on:
      - db
    environment:
      - MIX_ENV=test
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=db
    volumes:
      - .:/app
    command: mix test
    
    
