version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    image: phoenix-base
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: mix phx.server
  test:
    build:
      context: .
    image: phoenix-base-test
    depends_on:
      - db
    environment:
      - MIX_ENV=test
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=db
    volumes:
      - .:/app
    command: mix test
    
    
